#!/bin/bash

volume=$(pamixer --get-volume)
prev_volume=$volume

while :
do
    sleep 1 
    volume=$(pamixer --get-volume)

    if [ "$volume" != "$prev_volume" ]
    then
        eww update volume-hidden='true' -c /home/ayx/.config/eww/volume-indicator
        prev_volume=$volume
        sleep 1

        new_volume=$(pamixer --get-volume)
        if [ "$new_volume" != "$prev_volume" ]
        then
            continue
        else
            eww update volume-hidden='false' -c /home/ayx/.config/eww/volume-indicator
            prev_volume=$volume
        fi
    fi
done
