#!/bin/bash

REMOTE_FILE="u0_a259@localhost:/data/data/com.termux/files/usr/var/log/nginx/access.log"
LOCAL_FILE="$HOME/pub/logs/nginx.log"
PORT=8022

while true; do
  clear
  scp -q -s -P $PORT $REMOTE_FILE $LOCAL_FILE & 
  tail -F $LOCAL_FILE & #> /tmp/tail_output.log &
  TAIL_PID=$!
  sleep 1
  kill $TAIL_PID
done
