#!/bin/bash

if [[ $1 == "-f" ]]; then
    adb forward tcp:8022 tcp:8022 1>/dev/null
    adb forward tcp:8080 tcp:8080 1>/dev/null
    echo "SSH and HTTP ports are forwarded to localhost."
else
    adb forward --remove-all
    echo "Removed all forwarded ports."
fi

