#!/bin/bash

link=$(cliphist list | head -n1 | awk '{print $2}')
filename=$(printf | dmenu -b -p "filename: ")

if [ -z "$filename" ]; then
    exit 1
else
    wget $(yt-dlp -f b --get-url "$link") -O $HOME/vids/ytvids/$filename
    notify-send "Done" "Video is saved to ~/vids/ytvids/$filename"
fi

