#!/bin/bash

STATE=$(hyprctl -j getoption decoration:blur:passes | jq ".int")

if [ "${STATE}" == "3" ]; then
  hyprctl keyword decoration:blur:size 3
	hyprctl keyword decoration:blur:passes 1
  notify-send -t 1060 "Normal blur"
else
  hyprctl keyword decoration:blur:size 7.8
  hyprctl keyword decoration:blur:passes 3 
  notify-send -t 1060 "Glassmorphism activated"
fi
