#!/bin/bash
iDIR="$HOME/.config/hypr/mako/icons"

notification(){
  notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/music.png" "Now Playing: $1" 
}

menu(){
printf "1. Lofi\n"
printf "2. DraaaaainGaaaang"
}

main() {
choice=$(menu | dmenu -b -p "Choose what to listen:" | cut -d. -f1)
case $choice in

1)
  notification "Lofi"
  mpv --shuffle --vid=no "https://play.streamafrica.net/lofiradio"
  return
;;
2)
   notification "Draaaain Gaaang" 
   mpv --shuffle --vid=no "https://youtube.com/playlist?list=PL8wO5xwxGU0n9Z4yTEhTJcm2pp2pjjyZO"
   return
;; 
esac
}

pkill -f http && notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/music.png" "Online Music stopped" || main

