#!/bin/bash

iDIR="$HOME/.config/hypr/mako/icons"

time=$(date +%Y-%m-%d-%H-%M-%S)
dir="$(xdg-user-dir)/pics/Screenshots"
file="Screenshot_${time}_${RANDOM}.png"

notify_cmd_shot="notify-send -i ${iDIR}/picture.png"
notify_view() {
	${notify_cmd_shot} "Copied to clipboard."
	if [[ -e "$dir/$file" ]]; then
		${notify_cmd_shot} "Screenshot Saved."
	else
		${notify_cmd_shot} "Screenshot Deleted."
	fi
}


shotnow() {
	cd ${dir} && grim - | tee "$file" | wl-copy
	notify_view
}

shot5() {
	cd ${dir} && grim - | tee "$file" | wl-copy
	echo $dir/$file | wl-copy 
	notify_view
}

shotwin() {
	w_pos=$(hyprctl activewindow | grep 'at:' | cut -d':' -f2 | tr -d ' ' | tail -n1)
	w_size=$(hyprctl activewindow | grep 'size:' | cut -d':' -f2 | tr -d ' ' | tail -n1 | sed s/,/x/g)
	cd ${dir} && grim -g "$w_pos $w_size" - | tee "$file" | wl-copy
	notify_view
}

shotarea() {
	cd ${dir} && grim -g "$(slurp -w 2)" - | tee "$file" | wl-copy
    echo $dir/$file | wl-copy
    notify_view
}

if [[ "$1" == "--now" ]]; then
	shotnow
elif [[ "$1" == "--in5" ]]; then
	shot5
elif [[ "$1" == "--win" ]]; then
	shotwin
elif [[ "$1" == "--area" ]]; then
	shotarea
else
	echo -e "Available Options : --now --in5 --in10 --win --area"
fi

exit 0
