#!/bin/bash

power() {
    LOCK_FILE_POWER="$HOME/.cache/eww-song.lock"

run() {
    eww open song -c ~/.config/eww/
}

if [[ ! -f "$LOCK_FILE_POWER" ]]; then
    eww close song -c ~/.config/eww/
    touch "$LOCK_FILE_POWER"
    run && echo "ok good!"
elif [[ -f "$LOCK_FILE_POWER" ]]; then
    eww close song -c ~/.config/eww/
    rm "$LOCK_FILE_POWER" && echo "closed"
fi
}

power
