#!/usr/bin/bash
ignore="firefox.instance$(pgrep firefox)"
status=$(playerctl status -i $ignore 2> /dev/null)
icon=""

sh ~/.config/hypr/scripts/songart.sh get

if [[ "$status" == "Playing" ]]; then
  icon=""
elif [[ "$status" == "Paused" ]]; then
  icon=""
fi

echo "$icon"

