#!/usr/bin/bash
#ignore="firefox.instance$(pgrep firefox)"

ignore=$(playerctl -l | grep firefox.instance | head -n1)
parg="-i $ignore"

if [ -z "$ignore" ]; then
  parg=""
else
  echo 1>/dev/null 
fi

status=$(playerctl status $parg 2> /dev/null)
icon=""

sh ~/.config/hypr/scripts/songart.sh get

if [[ "$status" == "Playing" ]]; then
  icon=""
elif [[ "$status" == "Paused" ]]; then
  icon=""
fi

echo "$icon"

