#!/bin/bash

dir="$HOME/.config/hypr"
gitdir="$HOME/downloads/git/Hyprland"

cdir() {
    cd $1
    $SHELL
}

if [ -z "$1" ]; then
    nvim "$dir/hyprland.conf"
elif [ $1 == "-g" ] || [ $1 == "--git" ]; then
    cdir "$gitdir" 
elif [ $1 == "-b" ]; then
    nvim "$dir/binds.conf" 
elif [ $1 == "-w" ]; then
    nvim "$dir/windowrules.conf"
elif [ $1 == "-p" ]; then
    nvim "$dir/plugins.conf"
elif [ $1 == "-d" ]; then
    cdir $dir
elif [ $1 == "-s" ]; then
    cdir $dir/scripts
elif [ $1 == "-os" ]; then
    nvim $dir/scripts
elif [ $1 == "-wb" ]; then
    nvim $dir/waybar/config.jsonc
elif [ $1 == "-ws" ]; then
    nvim $dir/waybar/style.css
elif [ $1 == "-u" ]; then
    echo "running \`git pull origin main\` in the hypr repo..."
    cd "$gitdir" 
    git pull origin main
    echo "updating submodules..."
    git submodule update --recursive --remote
elif [ $1 == "-gl" ]; then
    cd "$gitdir"
    git log --graph --oneline --decorate --all
elif [ $1 == "--log" ] || [ $1 == "log" ] || [ $1 == "-l" ]; then
    tail -f /tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprland.log
elif [ $1 == "-B" ] || [ $1 == "--back" ]; then
    read -p "are u sure u want to make a backup? (Y/n) " choice
    if [[ "$choice" == "Y" || "$choice" == "y" || -z "$choice" ]]; then
        cp $(which Hyprland) $HOME/templates/hypr/Hyprland
        cp $(which hyprctl) $HOME/templates/hypr/hyprctl
        echo "done"
    else
        echo "okay. exiting"
        exit 1
    fi
else
    echo "no such idk bruh yk what i mean lol" 
fi

