#!/bin/bash

command=$(hyprctl -j getoption input:kb_layout | jq -r .str)

if [ "$command" = "us,ua" ]; then
    hyprnotify "[layout] added eww lang :("
    hyprctl keyword input:kb_layout us,ua,ru
else
    hyprnotify "[layout] removed eww lang :)"
    hyprctl keyword input:kb_layout us,ua
fi

