#!/bin/bash

command=$(hyprctl -j getoption input:kb_layout | jq -r .str)

if [ "$command" = "us,ua" ]; then
    notify-send "layout" "added ru lang"
    hyprctl keyword input:kb_layout us,ua,ru
else
    notify-send "layout" "removed ru lang"
    hyprctl keyword input:kb_layout us,ua
fi

