#!/bin/bash

if [ -z $1 ]; then
    if grep -qs /dev/sda1 /proc/mounts; then
        echo "mount point is alredy mounted. exiting."
        exit 2
    else
        echo "mounting /dev/sda1 to /mnt/flashd..."
        sudo mount -t vfat -o uid=1000,gid=1000,umask=0022 /dev/sda1 /mnt/flashd/
        echo "/dev/sda1 is mounted to /mnt/flashd"
    fi
else
    echo "unmounting /dev/sda1 from /mnt/flashd...."
    sudo umount /mnt/flashd
    echo "/dev/sda1 is unmouted"
fi

